
server:
  port : 8081
  servlet:
    context-path: /sc

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/teacher?useCode=true&characterEncoding=UTF-8&serverTimeZone=ASIA/ShangHai
    username : root
    password: root
mybatis:
  mapper-locations: classpath:com/zueb/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl